### ISSUE TITLE
Does this library seem to not support ESLint?

### ISSUE THREAD

**Issue by wsy998** [posva/unplugin-vue-router#232]
My Node.js version is v18.17, TypeScript version is 5.2.2, and the package manager is pnpm,eslint version is 8.49. When I run `ESLint -fix`, I encounter the following error:

```
 error  Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './auto' is not defined by "exports" in D:\workspace\blogs\frontend\node_modules\vue-router\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at findModulePath (D:\workspace\blogs\frontend\node_modules\.pnpm\eslint-import-resolver-alias@1.1.2_eslint-plugin-import@2.28.1\node_modules\eslint-import-resolver-alias\index.js:99:27)
    at exports.resolve (D:\workspace\blogs\frontend\node_modules\.pnpm\eslint-import-resolver-alias@1.1.2_eslint-plugin-import@2.28.1\node_modules\eslint-import-resolver-alias\index.js:75:10)
    at withResolver (D:\workspace\blogs\frontend\node_modules\.pnpm\eslint-module-utils@2.8.0_@typescript-eslint+parser@5.62.0_eslint-import-resolver-node@0.3.9__ncnjxkvkijm55yp3hzjf6rdeaa\node_modules\eslint-module-utils\resolve.js:114:23)
    at fullResolve (D:\workspace\blogs\frontend\node_modules\.pnpm\eslint-module-utils@2.8.0_@typescript-eslint+parser@5.62.0_eslint-import-resolver-node@0.3.9__ncnjxkvkijm55yp3hzjf6rdeaa\node_modules\eslint-module-utils\resolve.js:135:22)
    at relative (D:\workspace\blogs\frontend\node_modules\.pnpm\eslint-module-utils@2.8.0_@typescript-eslint+parser@5.62.0_eslint-import-resolver-node@0.3.9__ncnjxkvkijm55yp3hzjf6rdeaa\node_modules\eslint-module-utils\resolve.js:84:10)  import/no-relative-packages

D:\workspace\blogs\frontend\src\routes\index.vue
  1:1  error  Component name "index" should always be multi-word  vue/multi-word-component-names
```

**Comment by wsy998** [comment]
However, Vite starts up normally without being affected.

**Comment by posva** [comment]
We probably need to add something like https://github.com/unplugin/unplugin-auto-import#eslint T some point. Or you could use the auto imports as shown in this read me and it will support the eslint config as shown in the other readme

**Comment by wsy998** [comment]
I forgot to mention that I am using unplugin-auto-import and have also enabled the .eslintrc for unplugin-auto-import, but I am still getting this error.

**Comment by ByScripts** [comment]
I also have a problem with ESLint.

```ts
import { createRouter, createWebHistory } from 'vue-router/auto'
```

Gives me the error:

> ESLint: Unable to resolve path to module 'vue-router/auto'.(import/no-unresolved)

**Comment by shaddollxz** [comment]
> I also have a problem with ESLint.
> 
> ```ts
> import { createRouter, createWebHistory } from 'vue-router/auto'
> ```
> 
> Gives me the error:
> 
> > ESLint: Unable to resolve path to module 'vue-router/auto'.(import/no-unresolved)

you can add this config in your .eslintrc.cjs(or other eslint config file)
```javascript
  settings: {
    'import/core-modules': ['vue-router/auto'],
  },
```

**Comment by posva** [comment]
I couldn't reproduce this anymore. Can anyone with a boiled down repro help? Thanks

**Comment by posva** [comment]
Closing due to inactivity. Please open a new issue with a reference to this one if you can follow up with more information.
