### ISSUE TITLE
Error causing HMR crashing.

### ISSUE THREAD

**Issue by eddie-englund** [posva/unplugin-vue-router#296]
Hey!

I've been digging into this weird issue where when I type away eventually a babel error is thrown crashing the dev sever and it appears to be related to this plugin!

This is the error:
```
[vue-tsc] Found 0 errors. Watching for file changes.
C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:348
    const error = new SyntaxError();
                  ^

SyntaxError: Unexpected token (101:35)
    at constructor (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:348:19)
    at TypeScriptParserMixin.raise (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:3202:19)    at TypeScriptParserMixin.unexpected (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:3232:16)
    at TypeScriptParserMixin.parseParenAndDistinguishExpression (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:11479:12)
    at TypeScriptParserMixin.parseExprAtom (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:11113:23)
    at TypeScriptParserMixin.parseExprSubscripts (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10839:23)
    at TypeScriptParserMixin.parseUpdate (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10822:21)
    at TypeScriptParserMixin.parseMaybeUnary (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10798:23)
    at TypeScriptParserMixin.parseMaybeUnary (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:9682:18)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10636:61)
    at TypeScriptParserMixin.parseExprOps (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10641:23)
    at TypeScriptParserMixin.parseMaybeConditional (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10618:23)
    at TypeScriptParserMixin.parseMaybeAssign (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10579:21)
    at TypeScriptParserMixin.parseMaybeAssign (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:9629:20)
    at C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10549:39
    at TypeScriptParserMixin.allowInAnd (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:12229:12)
    at TypeScriptParserMixin.parseMaybeAssignAllowIn (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10549:17)
    at TypeScriptParserMixin.parseExprListItem (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:11981:18)
    at TypeScriptParserMixin.parseCallExpressionArguments (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:11036:22)
    at TypeScriptParserMixin.parseCoverCallAndAsyncArrowHead (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10946:29)
    at TypeScriptParserMixin.parseSubscript (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10881:19)
    at TypeScriptParserMixin.parseSubscript (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:9153:18)
    at TypeScriptParserMixin.parseSubscripts (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10852:19)
    at TypeScriptParserMixin.parseExprSubscripts (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10843:17)
    at TypeScriptParserMixin.parseUpdate (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10822:21)
    at TypeScriptParserMixin.parseMaybeUnary (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10798:23)
    at TypeScriptParserMixin.parseMaybeUnary (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:9682:18)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10636:61)
    at TypeScriptParserMixin.parseExprOps (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10641:23)
    at TypeScriptParserMixin.parseMaybeConditional (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10618:23)
    at TypeScriptParserMixin.parseMaybeAssign (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10579:21)
    at TypeScriptParserMixin.parseMaybeAssign (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:9629:20)
    at C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10549:39
    at TypeScriptParserMixin.allowInAnd (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:12224:16)
    at TypeScriptParserMixin.parseMaybeAssignAllowIn (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:10549:17)
    at TypeScriptParserMixin.parseVar (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:13204:91)
    at TypeScriptParserMixin.parseVarStatement (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:13045:10)
    at TypeScriptParserMixin.parseVarStatement (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:9292:31)
    at TypeScriptParserMixin.parseStatementContent (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:12628:23)
    at TypeScriptParserMixin.parseStatementContent (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:9326:18)
    at TypeScriptParserMixin.parseStatementLike (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:12533:17)
    at TypeScriptParserMixin.parseModuleItem (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:12510:17)
    at TypeScriptParserMixin.parseBlockOrModuleBlockBody (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:13134:36)
    at TypeScriptParserMixin.parseBlockBody (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:13127:10)
    at TypeScriptParserMixin.parseProgram (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:12409:10)
    at TypeScriptParserMixin.parseTopLevel (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:12399:25)
    at TypeScriptParserMixin.parse (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:14295:10)
    at TypeScriptParserMixin.parse (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:9968:18)    at parse (C:\Users\Titus\code\work\aiq-backoffice-v2\node_modules\.pnpm\@babel+parser@7.22.16\node_modules\@babel\parser\lib\index.js:14336:38)
    at babelParse (file:///C:/Users/Titus/code/work/aiq-backoffice-v2/node_modules/.pnpm/ast-kit@0.9.4/node_modules/ast-kit/dist/index.js:168:31)
    at getSetupAst (file:///C:/Users/Titus/code/work/aiq-backoffice-v2/node_modules/.pnpm/@vue-macros+common@1.6.0_vue@3.3.4/node_modules/@vue-macros/common/dist/index.mjs:195:14)
    at extractDefinePageNameAndPath (file:///C:/Users/Titus/code/work/aiq-backoffice-v2/node_modules/.pnpm/unplugin-vue-router@0.6.4_vue-router@4.2.4_vue@3.3.4/node_modules/unplugin-vue-router/dist/chunk-YCEF6K2A.mjs:1018:20)
    at writeRouteInfoToNode (file:///C:/Users/Titus/code/work/aiq-backoffice-v2/node_modules/.pnpm/unplugin-vue-router@0.6.4_vue-router@4.2.4_vue@3.3.4/node_modules/unplugin-vue-router/dist/chunk-YCEF6K2A.mjs:1326:7)
    at async updatePage (file:///C:/Users/Titus/code/work/aiq-backoffice-v2/node_modules/.pnpm/unplugin-vue-router@0.6.4_vue-router@4.2.4_vue@3.3.4/node_modules/unplugin-vue-router/dist/chunk-YCEF6K2A.mjs:1349:5)
    at async file:///C:/Users/Titus/code/work/aiq-backoffice-v2/node_modules/.pnpm/unplugin-vue-router@0.6.4_vue-router@4.2.4_vue@3.3.4/node_modules/unplugin-vue-router/dist/chunk-YCEF6K2A.mjs:1359:7 {
  code: 'BABEL_PARSER_SYNTAX_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 101, column: 35, index: 3536 },
 
 ```

EDIT: More context.

Package.json

```json
{
  "name": "redacted",
  "version": "0.0.2",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite --mode development",
    "proxy:test": "vite --mode test",
    "proxy:dev": "vite --mode development",
    "preview": "vite preview",
    "test:unit": "vitest --environment jsdom",
    "build": "vite build",
    "type-check": "vue-tsc --noEmit -p tsconfig.vitest.json --composite false",
    "lint": "eslint ./src/ --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore",
    "format": "prettier --write src/",
    "storybook": "storybook dev -p 6006",
    "build-storybook": "storybook build"
  },
  "dependencies": {
    "@vue/compiler-sfc": "^3.4.7",
    "@vueuse/core": "^10.7.1",
    "billboard.js": "3.10.1",
    "classnames": "^2.3.2",
    "clsx": "^2.0.0",
    "d3-format": "3.1.0",
    "element-plus": "^2.4.3",
    "fuzzysort": "^2.0.4",
    "keycloak-js": "^22.0.1",
    "luxon": "^3.3.0",
    "papaparse": "^5.4.1",
    "pinia": "^2.1.6",
    "radash": "^11.0.0",
    "streamsaver": "^2.0.6",
    "ts-pattern": "^5.0.4",
    "uuid": "^9.0.1",
    "vue": "^3.3.4",
    "vue-router": "^4.2.4",
    "zod": "^3.22.3"
  },
  "devDependencies": {
    "@iconify-json/mdi": "^1.1.53",
    "@rushstack/eslint-patch": "^1.4.0",
    "@storybook/addon-essentials": "^7.1.1",
    "@storybook/addon-interactions": "^7.1.1",
    "@storybook/addon-links": "^7.1.1",
    "@storybook/addon-styling": "^1.3.4",
    "@storybook/blocks": "^7.1.1",
    "@storybook/testing-library": "^0.2.0",
    "@storybook/vue3": "^7.1.1",
    "@storybook/vue3-vite": "^7.1.1",
    "@tsconfig/node18": "^18.2.2",
    "@types/d3-format": "^3.0.4",
    "@types/jsdom": "^21.1.6",
    "@types/luxon": "^3.3.1",
    "@types/node": "^18.17.1",
    "@types/papaparse": "^5.3.8",
    "@types/streamsaver": "^2.0.1",
    "@types/uuid": "^9.0.7",
    "@vitejs/plugin-vue": "^5.0.2",
    "@vue/eslint-config-prettier": "^8.0.0",
    "@vue/eslint-config-typescript": "^11.0.3",
    "@vue/test-utils": "^2.4.1",
    "@vue/tsconfig": "^0.4.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.49.0",
    "eslint-plugin-import": "^2.29.0",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "eslint-plugin-storybook": "^0.6.13",
    "eslint-plugin-vue": "^9.17.0",
    "ic": "link:@iconify\\json\\ic",
    "jsdom": "^23.0.1",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.31",
    "prettier": "^3.0.0",
    "prettier-plugin-tailwindcss": "^0.4.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.64.2",
    "storybook": "^7.1.1",
    "tailwindcss": "^3.3.3",
    "ts-node": "^10.9.1",
    "tslib": "^2.6.2",
    "typescript": "~5.3.3",
    "unplugin-element-plus": "^0.8.0",
    "unplugin-icons": "^0.16.5",
    "unplugin-vue-components": "^0.25.1",
    "unplugin-vue-router": "^0.6.4",
    "vite": "^5.0.11",
    "vite-plugin-checker": "^0.6.2",
    "vitest": "^1.0.4",
    "vue-tsc": "^1.8.11"
  }
}
```

vite.config.ts

```ts
import { fileURLToPath, URL } from 'node:url';

import vue from '@vitejs/plugin-vue';
import ElementPlus from 'unplugin-element-plus/vite';
import Icons from 'unplugin-icons/vite';
import VueRouter from 'unplugin-vue-router/vite';
import { defineConfig } from 'vite';
import checker from 'vite-plugin-checker';

export default defineConfig({
  plugins: [
    VueRouter({
      routesFolder: 'src/pages',
      extensions: ['.vue']
    }), // NOTE: This must be before vue()
    vue(),
    Icons(),
    ElementPlus({}),
    checker({
      eslint: {
        lintCommand: 'eslint ./src',
        dev: { logLevel: ['error'] }
      },
      vueTsc: true
    })
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  // ignore stories from build
  build: {
    rollupOptions: {
      external: new RegExp('/.*stories.ts')
    }
  }
});
```

**Comment by eddie-englund** [comment]
Hi,

Unfortunately I can't share any code beyond this since it's a work project.

Is there anything else I can do to assist in investigating this issue?

**Comment by posva** [comment]
You could always investigate it by yourself. 
the issue is likely to be solved in the future (there are other issues about hmr)
If you manage to create a boiled down reproduction (minimal deps), open a new issue

**Comment by eddie-englund** [comment]
> You could always investigate it by yourself. the issue is likely to be solved in the future (there are other issues about hmr) If you manage to create a boiled down reproduction (minimal deps), open a new issue

Hi,

Thanks for letting me know. I'm not quite sure what the issue is and I simply managed to find out after some time that it was related to this project.

I'll see if I can create a minimal project at some point but I'm fairly busy at the moment.

Thanks for the consideration, and good luck! I love this project and what it's brought overall so only have this as a minor inconvenience is not that bad compared to the gains!
