### ISSUE TITLE
definePage() breaks code generation if route contain named views (index@topbar.vue), requiring restart of dev server

### ISSUE THREAD

**Issue by minenwerfer** [posva/unplugin-vue-router#338]
Reproduction:

1. Have a index@topbar.vue and a index.vue file.
2. Use definePage() in index.vue.
3. An error overlay should show up, requiring manual restart of vite to work again.

```
web| 12:01:18 AM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
web|   Plugin: vite:import-analysis
web|   File: /home/mega/omega/web/src/pages/dashboard/order/index@topbar.vue?definePage&vue:2:42
web|   1  |  <template>
web|   2  |    <aeria-crud-topbar></aeria-crud-topbar>
web|      |                                           ^
web|   3  |  </template>
web|   4  |  
web|       at formatError (file:///home/mega/omega/node_modules/vite/dist/node/chunks/dep-G-px366b.js:50545:46)
web|       at TransformContext.error (file:///home/mega/omega/node_modules/vite/dist/node/chunks/dep-G-px366b.js:50539:19)
web|       at TransformContext.transform (file:///home/mega/omega/node_modules/vite/dist/node/chunks/dep-G-px366b.js:65565:22)
web|       at async Object.transform (file:///home/mega/omega/node_modules/vite/dist/node/chunks/dep-G-px366b.js:50854:30)
web|       at async loadAndTransform (file:///home/mega/omega/node_modules/vite/dist/node/chunks/dep-G-px366b.js:53644:29)
web|       at async viteTransformMiddleware (file:///home/mega/omega/node_modules/vite/dist/node/chunks/dep-G-px366b.js:63438:32)
```

Version:

- `unplugin-vue-router@0.8.4`
- `vite@5.1.5`

**Comment by minenwerfer** [comment]
In `0.8.5` this doesn't raise an error anymore, but also the route data won't be set.
I have a `page.vue` and a `page@topbar.vue`. The `page.vue` file has the following inside script setup:

```ts
definePage({
  meta: {
    title: 'Follow up',
    icon: 'check'
  }
})
```
The `meta` property won't show this way, but it shows if I rename `page@topbar.vue` to something else.

**Comment by posva** [comment]
I tested in the playground and it works well with index.vue and index@named.vue
